### ISSUE TITLE
Ruby version support?

### ISSUE THREAD

**Issue by olleolleolle** [procore-oss/blueprinter#276]
Would it be time to update the CI matrix to in-support Ruby versions?

(Current status: Ruby 2.5 is EOL.)

**Comment by swiknaba** [comment]
bold claim: people running on Ruby <= 2.4 still use AMS instead of Blueprinter since Blueprinter isn't around since that long.

I.e. we could drop:
- 2.2
- 2.3
- 2.4

and add:
- 2.6
- 2.7
- 3.0

Also, if we perform the benchmark for each Ruby version, we can greatly simplify the CI script by using a test matrix (see the docs: https://circleci.com/blog/circleci-matrix-jobs/).

**Comment by jmeridth** [comment]
This is being addressed in #307.  We are switching to GitHub Actions and moving to maintained ruby versions.  2.7 will be handled separately for known legacy application.

**Comment by jmeridth** [comment]
New [0.26.0](https://rubygems.org/gems/blueprinter/versions/0.26.0) version has been released that is 2.7+
