### ISSUE TITLE
[Feature Request] Get access to the parent blueprint

### ISSUE THREAD

**Issue by jamesst20** [procore-oss/blueprinter#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Let's say I have a `Parent` and `Child` record.

If I render the `Child` blueprint, I might want to include the parent record as such

```
{
  ...child_attributes
  parent: { ...parent_attributes_without_childs }
}
```

If I render the `Parent` blueprint, I might want to include the childs records as such

```
{
  ...parent_attributes
  child: [{ ...child_attributes_without_parent }]
}
```

### Describe the feature you'd like to see implemented

```ruby
class ParentBlueprint
  fields :name

  association :children, blueprint: ChildBlueprint, view: :children, if: -> { not_rendered_by_child_blueprint }
end

class ChildBlueprint
  fields :name

  association :parent, blueprint: ParentBlueprint, view: :parent, if: -> { not_rendered_by_parent_blueprint }
end
```

### Describe alternatives you've considered

Well of course I can define many views to get the same results, but it seems it would be cleaner to just remove the attribute based on that condition

**Comment by lessthanjacob** [comment]
Hey @jamesst20! This is an interesting use case, but I'm not confident that it's worth implementing with how the rendering logic is currently implemented (primarily in the context of added complexity). 

I'd actually argue that the view approach would be cleaner here IMO:

```ruby
class ParentBlueprint < Blueprinter::Base
  field :name 
  
  view :with_children do
    association :children, blueprint: ChildBlueprint, view: :default
  end
end

class ChildBlueprint < Blueprinter::Base
  field :name 

  view :with_parent do
    association :parent, blueprint: ParentBlueprint, view: :default
  end
end
```

This does put more onus on the caller of the initial `render` to provide the desired view, but I'd be curious as to the use case where this wouldn't be reasonable, and why we'd want to attempt to do this dynamically. Otherwise, you may be able to do this with some `options` handling, but I'd need to take another look!
