### ISSUE TITLE
[bug] Can't use blueprinter outside of rails with ActiveModels

### ISSUE THREAD

**Issue by Rudis1261** [procore-oss/blueprinter#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

- [ ] Yes, this used to work before

### Current Behavior

It's failing when using ActiveModels outside of rails:

```ruby
NameError: uninitialized constant Blueprinter::Configuration::JSON
  /usr/local/rvm/gems/ruby-2.7.4/gems/blueprinter-1.0.2/lib/blueprinter/configuration.rb:17:in `initialize'
  /usr/local/rvm/gems/ruby-2.7.4/gems/blueprinter-1.0.2/lib/blueprinter/configuration.rb:53:in `new'
```

### Expected Behavior

It should instantiate successfully. And should not rely on ActiveModel internals 🤷 We use ActiveModels for bin scripts for the structure it provides without needing an entire rails setup. For us it's a valid use case not to include the JSON serialiser by default. 

### Steps To Reproduce

Gemfile:
- blueprinter (1.0.2)

Tried to create a blueprint for an ActiveModel used outside of rails. It causes this exception until I add the include `include ActiveModel::Serializers::JSON`.

### Environment

```markdown
- OS: OSX 14.3.1
- Browser Name and version: N/A
- Ruby Version: ruby 2.7.4p191
```

### Anything else?

The models / blueprints in question

```ruby
class Delivery
  include ActiveModel::Model
  include ActiveModel::Attributes
  include ActiveModel::Serializers::JSON

  STATUSES = [:ok, :failed]
  TRANSPORTS = [:local, :remote]

  attribute :message_id, :string
  attribute :recipient_address, :string
  attribute :spamexperts_id, :string
  attribute :transport, inclusion: { in: TRANSPORTS }
  attribute :spambucketed, :boolean
  attribute :remote_host, :string
  attribute :remote_ip, :string
  attribute :timestamp, :date
  attribute :error, :boolean
  attribute :error_message, :string
  attribute :status, inclusion: { in: STATUSES }

  validates :recipient_address, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'must be a valid email address' }
end

class DeliveryBlueprint < Blueprinter::Base
  fields :message_id, :recipient_address, :spamexperts_id, :transport, :spambucketed
  fields :remote_host, :remote_ip, :timestamp, :error, :error_message, :status
end

class Message
  include ActiveModel::Model
  include ActiveModel::Attributes
  include ActiveModel::Serializers::JSON

  STATUSES = [:ok, :failed]
  attribute :message_id, :string
  attribute :sender_address, :string
  attribute :subject, :string
  attribute :size, :integer
  attribute :deliveries, default: []
  attribute :timestamp, :date
  attribute :error, :boolean
  attribute :error_message, :string
  attribute :status, inclusion: { in: STATUSES }

  validates :sender_address, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'must be a valid email address' }
  validates :deliveries, array_model: { with: Delivery }
end


class MessageBlueprint < Blueprinter::Base
  fields :message_id, :sender_address, :subject, :size, :timestamp, :error, :error_message, :status

  association :deliveries, blueprint: DeliveryBlueprint
end
```

**Comment by lessthanjacob** [comment]
Hey @Rudis1261! Thanks for opening this issue!

I was planning on addressing this as part of another issue, but I can open a quick PR to resolve this. There's a long standing _implicit_ dependency on the `JSON` library for the default configuration:

https://github.com/procore-oss/blueprinter/blob/ae408fb424c7c3f679006f895ba10116cd52d5a9/lib/blueprinter/configuration.rb#L17

This library is usually available in most use cases (e.g. in a Rails application), but it really should be _explicitly_ required if it's the default use case. 

> It should instantiate successfully. And should not rely on ActiveModel internals 🤷

Just wanted to note that this library isn't dependent on `ActiveModel` internals. The reason why this works after you `include ActiveModel::Serializers::JSON` is because _that_ module requires `JSON` as part of it's [dependencies](https://github.com/rails/rails/blob/55c4adeb36eff229972eecbb53723c1b80393091/activesupport/lib/active_support/core_ext/object/json.rb#L4).

If you'd like a temporary workaround, you can add a `require 'json'` where you're configuring `Blueprinter`.

**Comment by Rudis1261** [comment]
Ahhh yes that makes sense, sorry I didn't dig into each lib to try and trace why this was happening 🙈 It makes sense now looking at the error, because it wasn't looking at the top scope JSON, I made a false assumption🤣

Should have dug a bit deeper. Thanks for the MR to make it explicit 🙏
